# Generated by Django 4.0.2 on 2022-05-26 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_album'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='Album',
        ),
    ]
