# Generated by Django 4.0.2 on 2022-05-26 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_album_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table=None,
        ),
    ]
